// <auto-generated />
using BibleAppCore.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BibleAppCore.DataLayer.Migrations
{
    [DbContext(typeof(BibleDbContext))]
    partial class BibleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BibliaApp.BookDomainObject", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("BookFullName")
                        .HasMaxLength(50);

                    b.Property<int>("BookGlobalNumber");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SubbookNumber");

                    b.HasKey("Guid");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BibliaApp.BookExtendedDomainObject", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("BookFullName")
                        .IsRequired()
                        .HasMaxLength(8000);

                    b.Property<int>("BookGlobalNumber");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("NextBookGuid");

                    b.Property<string>("PassagesJson")
                        .IsRequired()
                        .HasMaxLength(8000);

                    b.Property<Guid>("PreviousBookGuid");

                    b.Property<int>("SubbookNumber");

                    b.HasKey("Guid");

                    b.ToTable("BookExtended");
                });

            modelBuilder.Entity("BibliaApp.CommentDomainObject", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<Guid>("BookGuid");

                    b.Property<string>("EndIndex")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<bool>("IsAudioFile");

                    b.Property<bool>("IsYoutubeVideo");

                    b.Property<Guid>("ManageCommentKeyGuid");

                    b.Property<string>("StartIndex")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.HasKey("Guid");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BibliaApp.PassageDomainObject", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("BookGuid");

                    b.Property<string>("Meantitle1");

                    b.Property<string>("Meantitle2");

                    b.Property<int>("PassageNumber");

                    b.Property<string>("PassageText")
                        .IsRequired()
                        .HasMaxLength(8000);

                    b.Property<string>("Title1");

                    b.Property<string>("Title2");

                    b.HasKey("Guid");

                    b.ToTable("Passage");
                });

            modelBuilder.Entity("BibliaApp.UserDomainObject", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Guid");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
